### ISSUE TITLE
Update requires "Access your data on all websites"

### ISSUE THREAD

**Issue by Hubro** [brcontainer/stack-exchange-notifications#10]
``` text
To update the extension "StackExchange Notifications", you must confirm, due to new permissions:

  * Access your data on all websites

Do you want to update?
```

What on earth does the extension need this for?

**Comment by brcontainer** [comment]
@Hubro It is necessary because this script: https://github.com/brcontainer/stack-exchange-notifications/blob/master/chrome/js/detectuseractivity.js

Unfortunately Desktop notifications not work complementamente in Opera and Firefox, the parameter "requestInteration" only works pro GoogleChrome.

So I created this feature to detect whether the user is still in using the computer (still experimental).

When Firefox and Opera implement the "requestInteration" then I will remove this ([manifest.json#L47](https://github.com/brcontainer/stack-exchange-notifications/blob/master/chrome/manifest.json#L47)):

```
    }, {
        "matches": [
            "<all_urls>"
        ],
        "js": [
            "js/detectuseractivity.js"
        ]
    }],
```

Thanks for asking and use the extension :)
